FROM cowrie/cowrie:latest
COPY userdb.txt /cowrie/cowrie-git/etc/userdb.txt
COPY filesystem/home /cowrie/cowrie-git/share/cowrie/honeyfs/home
COPY filesystem/etc /cowrie/cowrie-git/share/cowrie/honeyfs/etc
COPY filesystem/var /cowrie/cowrie-git/share/cowrie/honeyfs/var
EXPOSE 2222 2223
