input {
  beats {
    port => 5044
  }
  file {
    path => "/var/log/honeypot/cowrie/*.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    type => "cowrie"
  }
}
